'use strict';
let data,mode='play',category=null,quiz=null,selected=null,answered=false,errors=[],answers=0,correct=0,companyType='limited';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles={play:'今天，接下哪一個任務？',journal:'把交易，翻譯成分錄。',company:'從公司型態，到設立章程。',laws:'每個判斷，都找得到依據。',updates:'法規有變，題目也要跟上。',mistakes:'再練一次，把盲點變強項。'};
function law(id){return data.laws.find(l=>l.id===id)}
function article(ref){return law(ref.law)?.articles.find(a=>a.number===ref.article)}
function eligible(q){return q.status==='reviewed'&&q.refs.every(r=>article(r)?.text===r.baselineText&&!law(r.law)?.fetchError)&&q.refs.every(r=>(Date.now()-new Date(law(r.law).checkedAt).getTime())<31*86400000)}
function refsHTML(q){return `<div class="law-buttons">${q.refs.map(r=>`<button class="law-button" data-law="${esc(r.law)}" data-article="${esc(r.article)}">${esc(law(r.law)?.name)} 第${esc(r.article)}條</button>`).join('')}</div>`}
function switchView(v){mode=v;quiz=null;$('#page-title').textContent=titles[v];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render();window.scrollTo({top:0,behavior:'smooth'})}
function render(){if(!data)return;$('#mistake-count').textContent=errors.length;$('#review-date').textContent='資料核對 '+new Date(data.updatedAt).toLocaleDateString('zh-TW');$('#github').href=data.github;const pending=data.questions.filter(q=>!eligible(q)).length;$('#global-status').textContent=pending?`${pending} 道題目因條文變動、來源失敗或核對逾期暫停計分。請到「法規更新」查看。`:'';if(quiz)return renderQuiz();({play:renderHome,journal:renderJournal,company:renderCompany,laws:renderLaws,updates:renderUpdates,mistakes:renderMistakes}[mode]||renderHome)()}
function renderHome(){const count=data.questions.filter(eligible).length;$('#view').innerHTML=`<div class="intro"><p>選一個領域，完成情境任務。每題答完，立即看解析與法條。</p><span class="pill">核心情境 · 初學到實務</span></div><div class="stats"><div class="stat"><div class="stat-icon">◈</div><div><small>可挑戰題目</small><strong>${count}<em>道任務</em></strong></div></div><div class="stat"><div class="stat-icon">§</div><div><small>收錄法規全文</small><strong>${data.laws.length}<em>部法規</em></strong></div></div><div class="stat"><div class="stat-icon">◎</div><div><small>本輪答題正確率</small><strong>${answers?Math.round(correct/answers*100):0}%<em>${answers} 次答題</em></strong></div></div></div><div class="workspace"><div><div class="section-head"><h2>任務地圖</h2><span>CHOOSE YOUR CHAPTER</span></div><div class="chapters">${data.chapters.map((c,i)=>`<article class="chapter" style="--accent:${c.color}"><div class="chapter-top"><span class="badge">${esc(c.tag)}</span><span class="number">0${i+1}</span></div><h3>${esc(c.name)}</h3><p>${esc(c.description)}</p><div class="chapter-bottom"><span>${data.questions.filter(q=>q.category===c.id&&eligible(q)).length} 道情境任務</span><button data-start="${c.id}">開始闖關</button></div></article>`).join('')}</div></div><div class="side-panel"><article class="daily"><div class="label">MIXED CHALLENGE</div><h3>客戶一個問題，<br>常常跨越三種規則。</h3><p>隨機抽 10 題，練習切換帳務、人資與法規的思考。</p><button data-start="mixed">綜合實戰 · 10 題</button></article><article class="tips"><span class="mini-label">實務提醒</span><h3>先分清楚，才不會算錯。</h3><p>一般保費、個人補充保費、投保單位補充保費，不能混為一筆。</p><button class="quiet" data-law="L0060001" data-article="34">查看健保法第34條</button></article><article class="tips"><span class="mini-label">資料涵蓋</span><p>${esc(data.coverage)}</p></article></div></div>`}
function shuffled(arr){return arr.map(x=>({x,n:Math.random()})).sort((a,b)=>a.n-b.n).map(t=>t.x)}
function start(cat,items){const pool=(items||data.questions.filter(q=>cat==='mixed'||q.category===cat)).filter(eligible);if(!pool.length){alert('此領域目前沒有可計分的題目，請先更新及核對法規。');return}category=cat;quiz={questions:shuffled(pool).slice(0,cat==='mixed'?10:pool.length),index:0,score:0,results:[]};selected=null;answered=false;renderQuiz()}
function renderQuiz(){const q=quiz.questions[quiz.index];if(!q)return renderResult();$('#view').innerHTML=`<div class="quiz-wrap"><div class="quiz-top"><button class="quiet" data-exit>返回任務地圖</button><span class="quiz-meta">${category==='mixed'?'綜合實戰':esc(data.chapters.find(c=>c.id===q.category)?.name)} · ${quiz.index+1} / ${quiz.questions.length} 題 · 已答對 ${quiz.score} 題</span></div><div class="progress-track"><div style="width:${quiz.index/quiz.questions.length*100}%"></div></div><article class="question-card"><div class="question-label">CASE ${String(quiz.index+1).padStart(2,'0')} / 實務情境</div><h2>${esc(q.title)}</h2><p class="scenario">${esc(q.prompt)}</p><div class="options">${q.options.map((o,i)=>`<button class="option ${selected===i?'selected ':''}${answered&&(i===q.answer)?'correct ':''}${answered&&selected===i&&i!==q.answer?'wrong':''}" data-option="${i}" ${answered?'disabled':''}><span class="key">${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join('')}</div>${answered?`<div class="feedback ${selected===q.answer?'correct':'wrong'}" role="status"><strong>${selected===q.answer?'判斷正確，這筆任務結案！':'先記住原因，下次就更穩。'}</strong><p>${esc(q.explanation)}</p>${refsHTML(q)}<p style="font-size:12px;margin:12px 0 0">題目核對日 ${esc(q.reviewedAt)} · 展開法條可查看全文及官方來源</p></div>`:''}<div class="actions"><span class="hint">選擇最符合這個情境的答案。</span>${answered?`<button class="btn" data-next>${quiz.index+1===quiz.questions.length?'查看挑戰結果':'下一題'}</button>`:`<button class="btn" data-submit ${selected===null?'disabled':''}>確認答案</button>`}</div></article></div>`}
function submit(){if(selected===null||answered)return;const q=quiz.questions[quiz.index];if(!eligible(q)){alert('本題法規狀態已變，請重新載入資料。');return}answered=true;answers++;const yes=selected===q.answer;if(yes){quiz.score++;correct++;errors=errors.filter(e=>e.id!==q.id)}else if(!errors.some(e=>e.id===q.id))errors.push(q);quiz.results.push({id:q.id,correct:yes});$('#mistake-count').textContent=errors.length;renderQuiz()}
function renderResult(){$('#view').innerHTML=`<div class="card result"><span class="pill">挑戰完成</span><div class="big">${Math.round(quiz.score/quiz.questions.length*100)}<span style="font-size:20px">分</span></div><h2>${quiz.score===quiz.questions.length?'全數結案，今天很穩！':'每一個錯題，都是下一次的提示。'}</h2><p>答對 ${quiz.score} / ${quiz.questions.length} 題。<br>本輪錯題可立即再練；離開頁面後本輪紀錄會清除。</p><button class="btn" data-view="play">返回任務地圖</button> <button class="btn secondary" data-view="mistakes">複習本輪錯題</button></div>`}
function renderMistakes(){$('#view').innerHTML=errors.length?`<div class="intro"><p>本輪 ${errors.length} 道錯題。答對後會從清單移除。</p><button class="btn" data-review-errors>重新挑戰錯題</button></div>${errors.map(q=>`<article class="card"><h2>${esc(q.title)}</h2><p>${esc(q.prompt)}</p><p><strong>正確答案：</strong>${esc(q.options[q.answer])}</p><p>${esc(q.explanation)}</p>${refsHTML(q)}</article>`).join('')}`:`<div class="card empty">目前沒有本輪錯題。<br>開始闖關，將實務判斷練熟！</div>`}
function showLaw(id,num){const l=law(id);if(!l)return;const a=l.articles.find(x=>x.number===num);$('#law-dialog-content').innerHTML=`<p style="font-size:13px;color:#748294">${esc(l.name)} · 公布／修正：${esc(l.revision)}<br>資料取得：${esc(l.checkedAt)}${l.notice?'<br>'+esc(l.notice):''}</p>${(a?[a]:l.articles).map(articleHTML).join('')}<p><a href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">開啟官方法規全文</a></p>`;$('#law-dialog').showModal()}
function articleHTML(a){return `<div class="article"><h4>${esc(a.label)}</h4><pre>${esc(a.text)}</pre><a href="${esc(a.url)}" target="_blank" rel="noopener noreferrer">官方條文及沿革</a></div>`}
function renderLaws(){const previous=$('#law-search')?.value||'';$('#view').innerHTML=`<div class="intro"><p>搜尋已收錄法規的名稱、條號或內文。官方公布／修正日期與施行日期可能不同。</p></div><div class="search-row"><input type="search" id="law-search" placeholder="搜尋：特休、補充保險費、章程…" value="${esc(previous)}" aria-label="搜尋法規"><select id="law-category" aria-label="法規領域"><option value="all">全部領域</option>${data.chapters.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div id="law-results"></div>`;filterLaws()}
function filterLaws(){const term=$('#law-search').value.trim(),cat=$('#law-category').value;const ls=data.laws.filter(l=>(cat==='all'||l.category===cat)&&(!term||l.name.includes(term)||l.articles.some(a=>a.text.includes(term)||a.label.includes(term))));$('#law-results').innerHTML=`<div class="law-list">${ls.map(l=>{const arts=term&&!l.name.includes(term)?l.articles.filter(a=>a.text.includes(term)||a.label.includes(term)):l.articles;return `<article class="law-item"><h3>${esc(l.name)}</h3><div class="meta">公布／修正日期：${esc(l.revision)} · 取得日：${esc(l.checkedAt)} · ${l.articles.length} 條<br>${esc(l.notice||'完整適用及施行資訊請核對官方沿革。')} ${l.fetchError?'<span class="status-chip warn">最新抓取失敗</span>':''}</div><details><summary>展開${term?'搜尋結果':'法規全文'}（${arts.length} 條）</summary>${arts.map(articleHTML).join('')}</details></article>`}).join('')||'<div class="card empty">沒有符合的已收錄條文。請換個關鍵字。</div>'}</div>`}
const types={limited:{name:'有限公司',refs:['98','101','108'],description:'一人以上股東；全體股東同意章程；至少一人、最多三人董事。',check:'公司法第101條列示的必載事項'},stock:{name:'股份有限公司',refs:['128','128-1','129','130'],description:'一般發起人及政府、法人單一股東有不同規定；依設立方式完成法定程序。',check:'公司法第129條基本必載與第130條相對必載事項'},closed:{name:'閉鎖性股份有限公司',refs:['356-1','356-2','356-3','356-5'],description:'非公開發行、股東人數與轉讓限制適用特別規定；技術、勞務出資须另核對。',check:'公司法第356-2條及第356-5條等特別章程事項'},unlimited:{name:'無限公司',refs:['40','41'],description:'至少二名股東，其中半數在國內有住所；股東負連帶無限責任。',check:'公司法第41條章程必載事項'},mixed:{name:'兩合公司',refs:['114','115','116'],description:'由無限責任及有限責任股東組成；適用無限公司的準用規範及特別要求。',check:'公司法第41條、第115條及第116條的準用與特別要求'}};
function renderCompany(){const t=types[companyType];const ref=t.refs.map(n=>({law:'J0080001',article:n}));$('#view').innerHTML=`<div class="intro"><p>先選組織型態，再核對設立與章程。這裡是學習工坊，並非送件用自動章程。</p></div><div class="company-types">${Object.entries(types).map(([id,x])=>`<button class="type-btn ${id===companyType?'active':''}" data-company="${id}">${esc(x.name)}</button>`).join('')}</div><div class="split"><div><article class="card"><h2>${esc(t.name)}</h2><p>${esc(t.description)}</p><div class="notice">${esc(t.check)}。逐條展開閱讀，不能將不同公司類型的章程直接套用。</div>${refsHTML({refs:ref})}</article><article class="card"><h2>設立文件核對</h2>${[['名稱與所營事業','先辦理名稱、業務預查；許可業務另確認許可。'],['所在地與使用資格','確認地址、建物及土地使用規定，取得必要證明。'],['股東／發起人及章程','依選定型態訂立章程，填妥法定必載事項並簽章。'],['出資與資本查核','備妥出資證明與會計師資本額查核簽證。'],['組織及決議文件','依型態完成董事、監察人及相關會議、同意文件。'],['設立登記及後續申辦','依管轄機關規定送件，再辦稅籍及依法開立發票；僱員另辦投保與勞退。']].map(([a,b])=>`<label class="check-row"><input type="checkbox"><span><strong>${a}</strong><small>${b}</small></span></label>`).join('')}<p style="font-size:12px">勾選是本頁練習，重新切換型態即清除。文件及程序須以管轄機關實際要求為準。</p></article></div><div><article class="card"><h2>章程條文直接看</h2>${ref.map(r=>article(r)).filter(Boolean).map(articleHTML).join('')}</article><article class="card"><h2>延伸型態</h2><p>獨資／合夥商業、有限合夥、外國公司在臺分公司，適用不同登記與文件規範，未納入此版的完整操作課程。特殊許可業務、公開發行及外資投資亦需另核對。</p><button class="btn secondary" data-start="company">練習公司設立情境</button></article></div></div>`}
const journalCases=[{name:'收到已完成服務的現金款',amount:10000,debit:'現金',credit:'服務收入',reason:'資產增加記借方；已完成服務的收入增加記貸方。'},{name:'支付本月辦公室租金',amount:20000,debit:'租金費用',credit:'銀行存款',reason:'本期費用增加記借方；銀行存款減少記貸方。'},{name:'收回先前入帳的應收款',amount:15000,debit:'銀行存款',credit:'應收帳款',reason:'收到銀行款，同時減少應收款，不重複認列收入。'},{name:'收到銀行借款',amount:100000,debit:'銀行存款',credit:'借款',reason:'銀行存款與借款負債同時增加。'},{name:'先收尚未提供服務的訂金',amount:8000,debit:'現金',credit:'預收款',reason:'尚須提供服務，先列預收負債。'}];let journalIndex=0;
function renderJournal(){const c=journalCases[journalIndex],opts=['請選擇科目','現金','銀行存款','應收帳款','預收款','借款','租金費用','服務收入'];$('#view').innerHTML=`<div class="quiz-wrap"><div class="card"><span class="pill">借貸配對 · 情境 ${journalIndex+1} / ${journalCases.length}</span><h2 style="margin-top:22px">${c.name}</h2><p>金額：NT$ ${c.amount.toLocaleString()}。此練習忽略營業稅、扣繳及補充保費，專注於借貸方向。</p><div class="journal">${[['debit','借方'],['credit','貸方']].map(([id,label])=>`<label class="journal-row"><span>${label}</span><select id="journal-${id}" aria-label="${label}科目">${opts.map(o=>`<option>${o}</option>`).join('')}</select></label>`).join('')}</div><div id="journal-feedback"></div><div class="actions"><button class="btn" data-journal-check>核對分錄</button><button class="btn secondary" data-journal-next>換個情境</button></div></div><div class="notice">科目名稱為教學範例，實際入帳須依會計制度、交易實質與稅務規定確認。</div></div>`}
function checkJournal(){const c=journalCases[journalIndex],ok=$('#journal-debit').value===c.debit&&$('#journal-credit').value===c.credit;$('#journal-feedback').innerHTML=`<div class="feedback ${ok?'correct':'wrong'}"><strong>${ok?'借貸配對正確！':'再看一下交易方向。'}</strong><p>借：${c.debit} ${c.amount.toLocaleString()}<br>貸：${c.credit} ${c.amount.toLocaleString()}<br>${c.reason}</p>${refsHTML({refs:[{law:'J0080009',article:'10'},{law:'J0080009',article:'14'}]})}</div>`}
function renderUpdates(){$('#view').innerHTML=`<div class="intro"><p>重新取得法規全文。引用條文變動的題目會先暫停計分，重新核對後才恢復。</p><button class="btn" id="refresh" data-refresh>立即檢查法規</button></div><div class="card"><h2>更新狀態</h2><p>最近資料更新：${esc(new Date(data.updatedAt).toLocaleString('zh-TW'))}（你的裝置時間）</p><p>更新包含已收錄的全國法規資料庫條文；子法、函釋、費率表與公告並非全部自動涵蓋。新公告的公布日不等於施行日。</p><div id="refresh-status" role="status"></div><div class="notice">題目引用條文不同、來源抓取失敗或核對超過30日，會停止計分。更新全文不代表所有情境解析都已經重新審核。</div></div><div class="card"><h2>法規來源健康度</h2>${data.laws.map(l=>`<div class="update-row"><strong>${esc(l.name)}</strong> <span class="status-chip ${l.fetchError?'warn':''}">${l.fetchError?'抓取失敗':'已取得全文'}</span><p>公布／修正：${esc(l.revision)} · 取得：${esc(l.checkedAt)} ${l.fetchError?' · '+esc(l.fetchError):''}</p></div>`).join('')}</div><div class="card"><h2>變動紀錄</h2>${data.updates.length?data.updates.slice(-20).reverse().map(u=>`<div class="update-row"><strong>${esc(u.name||'更新檢查')}</strong><p>${esc(u.message)} · ${esc(new Date(u.at).toLocaleString('zh-TW'))}</p></div>`).join(''):'<p>初版內容已取得；尚無後續條文變動紀錄。</p>'}</div><div class="card"><h2>暫停計分題目</h2>${data.questions.filter(q=>!eligible(q)).map(q=>`<div class="update-row"><strong>${esc(q.title)}</strong><p>${esc(q.reviewReason||'來源核對逾期或條文需要重新核對。')}</p>${refsHTML(q)}</div>`).join('')||'<p>目前沒有暫停計分的題目。</p>'}</div>`}
async function refresh(){const b=$('#refresh');b.disabled=true;b.textContent='核對中…';$('#refresh-status').textContent='正在向官方來源取得法規，請稍候。';try{const r=await fetch('/api/refresh',{method:'POST',headers:{'X-Requested-With':'accounting-quest'}});const result=await r.json();if(!r.ok)throw Error(result.error||'更新失敗');data=await(await fetch('/api/content',{cache:'no-store'})).json();render();$('#refresh-status').textContent=result.message||'更新已完成。'}catch(e){$('#refresh-status').textContent='目前無法完成更新：'+e.message;b.disabled=false;b.textContent='重試檢查'}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)switchView(b.dataset.view);else if(b.dataset.start)start(b.dataset.start);else if(b.dataset.option!==undefined){selected=Number(b.dataset.option);renderQuiz()}else if(b.hasAttribute('data-submit'))submit();else if(b.hasAttribute('data-next')){quiz.index++;selected=null;answered=false;renderQuiz()}else if(b.hasAttribute('data-exit'))switchView('play');else if(b.dataset.law)showLaw(b.dataset.law,b.dataset.article);else if(b.dataset.company){companyType=b.dataset.company;renderCompany()}else if(b.hasAttribute('data-review-errors'))start('mixed',errors);else if(b.hasAttribute('data-journal-check'))checkJournal();else if(b.hasAttribute('data-journal-next')){journalIndex=(journalIndex+1)%journalCases.length;renderJournal()}else if(b.hasAttribute('data-refresh'))refresh();else if(b.id==='close-dialog')$('#law-dialog').close()});
document.addEventListener('input',e=>{if(e.target.id==='law-search')filterLaws()});document.addEventListener('change',e=>{if(e.target.id==='law-category')filterLaws()});
fetch('/api/content',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('伺服器暫時無法提供資料');return r.json()}).then(d=>{data=d;render()}).catch(e=>{$('#view').innerHTML=`<div class="card empty">${esc(e.message)}<br><button class="btn" onclick="location.reload()">重新載入</button></div>`});
